### ISSUE TITLE
Support camel-jq

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#136]
**Describe the solution you'd like**
jq is a powerful tool which is beyond just query but also for JSON transformation.
https://stedolan.github.io/jq/
And from Apache Camel 3.18.0 and i.e. from Camel-K 1.10.0, camel-jq will be supported, it then could be used for both Predicate and Expression
https://camel.apache.org/components/next/languages/jq-language.html

It would be a great addition as a transformation tool.

**Comment by joshiraez** [comment]
Isn't this sñolved by #152 ?

**Comment by joshiraez** [comment]
Or is it something else...?

Now that Im reading more about it, it would be great for more complex predicates/expressions, like what we need for the Aggregator EIP
