### ISSUE TITLE
Missing Salesforce sink in catalog

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-backend#191]
**Describe the bug**
I am unable to find a sink for Salesforce regardless if using integration or Kamelet/KameletBinding. Regarding the component description at https://camel.apache.org/components/3.18.x/salesforce-component.html there should be both consumer and producer available.

**Comment by Delawen** [comment]
Regarding kamelets, it is shown on the catalog:

![imagen](https://user-images.githubusercontent.com/726590/196700545-552d94b3-da40-4aac-8703-329cd072d3f6.png)

As this is a new kamelet, it could have been a problem with the camel-k version deployed on the server.
