### ISSUE TITLE
Add `required` to `properties` for /viewdefinition

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#25]
For the response of POST /viewdefinition we don't currently have a `required` property, and we probably should.

It would be good if we could support the JSON Schema keywords, particularly for validation:
- [JSON schema](http://json-schema.org/)
- [Ajv JSON schema keywords](https://ajv.js.org/json-schema.html) <-- we are using [Ajv](https://github.com/ajv-validator/ajv) for validation and [Uniforms](https://uniforms.tools/docs/api-bridges/#jsonschemabridge) to render the form fields automatically based on the schema

![Screen Shot 2022-01-14 at 12 23 12 pm](https://user-images.githubusercontent.com/3844502/149514990-e38ed0e0-ac44-406f-b6bd-ad5a9c7785c2.png)

**Comment by Delawen** [comment]
Ajv is a very specific implementation, right? Better to do the JSON schema.

**Comment by Delawen** [comment]
Sonarcloud complains because the test percentage coverage, but that really depends on the kamelet catalog we are testing...
