### ISSUE TITLE
[DSL] Support parsing of Syndesis JSON format

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-backend#28]
**Is your feature request related to a problem? Please describe.**
[Syndesis](https://syndesis.io/) users may want to migrate to Kaoto at some point. But Syndesis JSON format to store integrations is not interoperable.

As a syndesis user, I would like to be able to copy/paste a Syndesis JSON integration in the source code editor and/or upload a zip file so Kaoto understands it and returns the equivalent Camel route (or Kamelet binding).

**Describe the solution you'd like**
We just need to implement the `StepParserService` for Syndesis. Kaoto will return the translated step parsing to whatever output formats it has. To the extend this can be automated, obviously, some Syndesis specific steps may not be translatable.

**Comment by zregvart** [comment]
I think it's a bit more complex than translating one model to another, for this to happen the behavior of Syndesis connectors/runtime would need to be replicated or compensated in some way in Kaoto.

**Comment by lucamaf** [comment]
still needed ...
