### ISSUE TITLE
Update procedure to release

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#360]
**Is your feature request related to a problem? Please describe.**

the current way to release is based on update-version.sh script. It is not working completely given that now the main branch is protected.
Note also the "Publish executables" is currently not triggered automatically, see https://github.com/KaotoIO/kaoto-backend/issues/358

**Describe the solution you'd like**

- documentation in contributing.md
- updated script or provide another way to do it

**Describe alternatives you've considered**

**Additional context**

**Comment by apupier** [comment]
/!\ the tag created by the script should not be used as the tag on the repository because the commit are others due to the merge of the Pull Request.

For instance, for 0.6.0, the commit https://github.com/KaotoIO/kaoto-backend/commit/f4adaf6a7d84abd684426cedc0c4a311c5f64e2a is missing from v0.6.0. The v0.6.0 is based on branched path than the main.
The tag shoudl have been provided on https://github.com/KaotoIO/kaoto-backend/commit/da1c87ba28086bd8319c3b758c299044548da23e but it is on https://github.com/KaotoIO/kaoto-backend/commit/7c183744a6080b2faeb45305e11837e23c30fde3

A visual to better understand the current state:
![image](https://user-images.githubusercontent.com/1105127/214535832-65b3c740-f14c-434f-895b-bf1ea7d68bbe.png)

it is causing also troubles when generating the release notes as it is picking an older tag. (and ultimately would always take the same one if we always use this script)

**Comment by Delawen** [comment]
What I did for latest release is to push main in my fork and then do a PR from my fork. Would that be enough?

**Comment by apupier** [comment]
no, it is leading to the problem I mentioned. The tag is created on a commit which will be different than the one merged by the Pull request. So the pushed tag is not part of the main branch history.

![image](https://user-images.githubusercontent.com/1105127/220112986-588ee845-f50f-4e20-ae55-c88348ec3ac1.png)

the tag should be on the 3c2f11945584559976d046c6bb413841a19250a9 commit, not the 404b42947bc23b559dd14d226f875fcc399db036

**Comment by Delawen** [comment]
What is better, to unprotect the main branch or to have two stages for release? I am not sure myself :D

**Comment by apupier** [comment]
two stages for release.
it allows to have tests to be launched on a Pull request before creating the tag.
Also the update of other zip files should be provided in a different step to be also tested in a Pull Request before merging in main and ease review of pull request
