### ISSUE TITLE
[BUG] Kaoto backend not providing full list of kamelets from the catalog when connected to minikube

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-backend#380]
**Describe the bug**
The issue I'm facing is related to the response from the endpoint `http://localhost:8081/v1/steps?dsl=KameletBinding&namespace=default` 

The start and end kamelets are not present in the response - the only start kamelet present is the "knative" and the end ones are "knative-sink" and "stop EIP"

**To Reproduce**
1. run minikube locally with camel-k installed (kamelet catalog is present)
3. be logged into the minikube with kubectl
4. in the UI - view the kamelet catalog, or go to 
5. See error

**Expected behavior**
Previously the response provided all of the start and end kamelets from the kamelet catalog.

**Environment (please complete the following information):**
 - minikube with camel-k 1.10.2-nightly
 - Kaoto Version - built from latest master, running in dev mode (mvn quarkus:dev -pl api)

**Additional context**

**Comment by Delawen** [comment]
I think this is calling for strengthening the way we configure our sources for steps. Right now if there is a connection to a kubernetes cluster, it reads kamelets from there. But if the cluster is empty or you don't have privileges to read the kamelets, you may not get any.

**Comment by tplevko** [comment]
@Delawen with the latest Kaoto backend version, this no longer seems to be an issue. I think it can be closed
