### ISSUE TITLE
Provide native test corresponding to IntegrationsResourceTest

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#437]
**Is your feature request related to a problem? Please describe.**

Integrations api endpoint is tested through IntegrationsResourceTest, it is tested in JVM mode only.
it is important to have a test in native mode too.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Ideally, extending IntegrationsResourceTest would be nice and allows to have test added automatically picked up

**Comment by mkralik3** [comment]
remaining tests in `v1` done by https://github.com/KaotoIO/kaoto-backend/pull/774 and https://github.com/KaotoIO/kaoto-backend/pull/776
