### ISSUE TITLE
[BUG] Cannot set correctly path parameters when there is more than one

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#454]
**Describe the bug**

The parameter filled is set at a random position

![wrongPlaceForPathParam](https://user-images.githubusercontent.com/1105127/216104265-b66e809e-c2d4-436e-8e2c-2b8b56f02710.gif)

**To Reproduce**
1. Open a Camel Route
2. Add Avro component
3. Open text editor to vizualize
4. Select Avro node step and in config, set a value to Host
5. it will place the value as last param position instead of the third

You can also try with Message Name, it will place at second position instead of last position.

**Expected behavior**

place the parameter at correct place in Camel URI

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: Fedora
 - Output of the mvn -version` command
 - Kaoto Version main 1st February

**Additional context**

**Comment by Delawen** [comment]
Related to https://github.com/KaotoIO/kaoto-backend/issues/451

**Comment by Delawen** [comment]
A problem to solve this is that the JSON that defines the camel connector does not specify the proper order of the parameters. So there's no programmatical way of knowing unless we add an exception on the code for this specific connector.
