### ISSUE TITLE
[BUG] Created Camel components are serialized with only `:` as path parameter separator but `\` must be used in some places

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#455]
**Describe the bug**

When creating for instance an Avro component, it creates an uri like `uri: avro:null:null:null:null` although it shoudl be something like `uri: avro:null:null:null/null` see [doc](https://camel.apache.org/components/3.20.x/avro-component.html#_endpoint_options)

**To Reproduce**
1. Steps to reproduce the behavior:
2. Open a Camel Route
3. Add Avro component
4. Open text editor to vizualize

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: Fedora
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

**Comment by Delawen** [comment]
Related to https://github.com/KaotoIO/kaoto-backend/issues/451

**Comment by Delawen** [comment]
A problem to solve this is that the JSON that defines the camel connector does not specify the character to separate the parameters. So there's no programmatical way of knowing unless we add an exception on the code for this specific connector.
