### ISSUE TITLE
[BUG] No source step automatically makes the first step a source

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#46]
**Describe the bug**
When sending a list of steps to the `/customResource` endpoint, if there is no "source" step, then it automatically assumes the first step is a source, which is not always the case. For example, if a user deletes a source step, in the UI we leave a placeholder slot so that  they can drag a new source onto it. That's because we are trying to instruct the user that they should always provide a source.

**To Reproduce**
1. Send a list of steps to `/customResource` where the first step in the array is a middle step, or action

**Expected behavior**
It should return the steps in the exact same way they were sent, just in the correct format (e.g. YAML, JSON).

relates to https://github.com/KaotoIO/kaoto-ui/issues/231

**Comment by Delawen** [comment]
Should be fixed and merged in a few minutes.
