### ISSUE TITLE
Deleting first step when there are only 2 steps is deleting everything

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#475]
### Describe the Bug

Deleting first step when there are only 2 steps is deleting everything

### Steps to Reproduce the Bug or Issue

1. an integration with 2 steps
2. delete first step

--> the second one is deleted too

note that if there are 3 steps it is not the case.

### Screenshots or Videos

![removingAllSteps](https://user-images.githubusercontent.com/1105127/220125285-78b04859-d934-4b08-a5a4-264ccdd1bb24.gif)

### Platform

- OS: Fedora
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: Backend 0.6.2, frontend 0.6.1

**Comment by lhein** [comment]
looks like back end throwing away invalid code which is the case here as there is no source defined.
