### ISSUE TITLE
[BUG] YAML is rewritten after a sync

### ISSUE THREAD

**Issue by Croway** [KaotoIO/kaoto-backend#479]
**Describe the bug**
When pasting YAML routes Kaoto rewrites the route after a sync

**To Reproduce**
1. Go to [kaoto](http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/)
2. Click on Source Code
3. Paste the following content https://pastebin.com/5GjkzGfN
4. Click Sync your code
5. The route is rewritten

**Expected behavior**
The YAML should not be modified and the route should be displayed on the UI

**Additional context**
Here you can find simpler routes that have a similar issue https://pastebin.com/whLSSjGF https://pastebin.com/PGTzqY1h

**Comment by lhein** [comment]
sounds a bit related to [#666](https://github.com/KaotoIO/kaoto-ui/issues/666). Data loss is always bad.

**Comment by Delawen** [comment]
@lhein losing invalid data is not bad. But I am not going to go down that rabbit hole again because this doesn't seem related to that.

**Comment by lhein** [comment]
You will at some point have to go down that rabbit hole again. There is no way around, trust me.
