### ISSUE TITLE
Avoid adding parameters in the source code with default value

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-backend#503]
**Is your feature request related to a problem? Please describe.**
Step configuration parameters have sometimes default values which are also mentioned in the Camel Catalog. If you are dropping a timer component on the canvas and just change the name to `foo` it generates quite a lot of code which doesn't need to be there because its default values. (see screenshot)

![grafik](https://user-images.githubusercontent.com/435853/222689787-0cda4a67-1478-4b58-a4fa-9f1f5e63b668.png)

**Describe the solution you'd like**
Avoid generating code for default values of parameters. In the above example `uri: timer:foo` would have been enough.

**Comment by apupier** [comment]
duplicates of https://github.com/KaotoIO/kaoto-ui/issues/1365

**Comment by lhein** [comment]
Oh....thanks for pointing out, Aurelien. As this is a backend issue I wasn't checking in the UI issues.

**Comment by lhein** [comment]
adding another example which makes it even more obvious:
![grafik](https://user-images.githubusercontent.com/435853/222698544-c7283998-8b56-464d-889b-0d42fa2e7975.png)

**Comment by Delawen** [comment]
On the other hand, we have been requested to add those values explicitly...

**Comment by apupier** [comment]
> On the other hand, we have been requested to add those values explicitly...

i think, we were asked to have them visible in the UI. Not to have them serialized

**Comment by Delawen** [comment]
Just making sure. Because this was not happening before, so this is a new implementation (I think) based on that feedback.
