### ISSUE TITLE
[DSL] Support Common Workflow Language

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-backend#53]
This is a low priority enhancement. If you are interested in this feature, please express your interest in the comments.

**Describe the solution you'd like**

Support translation from [Common Workflow Language](https://github.com/common-workflow-language/common-workflow-language) to Camel.

To do this, implement the [StepParserService](https://kaoto.io/docs/add_dsl/) for Common Workflow Language.

**Describe alternatives you've considered**
If there is interest, we could also implement the DeploymentGeneratorService to generate CWL source code.

**Additional context**
This is a generic workflow language created several years ago used by some applications. It could be nice to be interoperable with it.

**Comment by alexkazan87** [comment]
Really interesting but I would like to see the workflow serverless language in camel generally. Please check this link: https://blog.kie.org/2021/12/implementing-the-filter-eip-using-camel-k-and-kogito.html
