### ISSUE TITLE
[BUG] - type property from the step's parameters field it is duplicated

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-backend#560]
**Describe the bug**
The `type` property from the step's parameter list is duplicated

**To Reproduce**
1. Make a `GET` call to
http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/api/v1/steps/id/debezium-mongodb-consumer?namespace=default
2. Open the RAW response detail
3. Notice how the `type` it's duplicated
![image](https://user-images.githubusercontent.com/16512618/226847425-d0b0d7e2-3a60-4bf1-8793-18b110e928e3.png)

**Expected behavior**
The key shouldn't be duplicated

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [OperateFirst]
 - Kaoto Version [0.7.4]

**Comment by lhein** [comment]
This issue doesn't occur any more on our nightly instance.

![grafik](https://github.com/KaotoIO/kaoto-backend/assets/435853/5c549971-6e05-43dc-a808-fc7382d48d59)

**Comment by lordrip** [comment]
@lhein could be the case that the previous screenshot is a parsed response?

At least in firefox, it's still happening, I copied the raw response and then format it using vscode
![image](https://github.com/KaotoIO/kaoto-backend/assets/16512618/e8838503-2c6a-4be9-b7a0-b753be83cef8)
