### ISSUE TITLE
[BUG] filepath of AtlasMap uri is wiped out on `sync code`

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#576]
**Describe the bug**

**To Reproduce**
1. Add a step
2. Add AtlasMap step
3. Select AtalsMap step
4. In Resource URi, provide a file path like `file:/etc/camel/resources/transform.adm` (inspired from q[uarkus superheroes example](https://github.com/pprosser-redhat/quarkus-super-heroes/blob/c530dd797f0ab35e50a0c07e6cf7cb4ab7c75a14/camelkfordebezium/camelformessaging/messaging.camel.yaml#L20))
5. Open source editor
6. Click on Sync code
7. --> only `file` is left

**Expected behavior**

the full path must be kept

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
OperateFirst

**Additional context**

**Comment by Delawen** [comment]
Oh, what a bad idea to use the same character separator `:` for field paths and for content inside the path field.

Working on it...
