### ISSUE TITLE
[BUG] If path parameters are containing several path parameter separator, only the first value is kept

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#591]
**Describe the bug**
If path parameters are containing several path parameter separator, only the first value is kept

**To Reproduce**
1. Add a step
2. Add a vertx-http step
3. In http Url, provide a value with a port specified like `https://www.test.com:8080/demo`
4. Open source code editor
5. click on sync code
6. --> the part `:8080/demo` is removed

**Expected behavior**

keep the full uri

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**

follow-up on #576

**Comment by Delawen** [comment]
I am testing on https://github.com/KaotoIO/kaoto-backend/pull/597 and I think this is already fixed there. 

![image](https://user-images.githubusercontent.com/726590/228826708-22c587ec-02a6-4934-afb3-58ee409a6dc5.png)
