### ISSUE TITLE
Upgrade to Quarkus 2.16.x

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#605]
**Is your feature request related to a problem? Please describe.**

latest and greatest versions of Quarkus are 2.16.x

**Describe the solution you'd like**

use latest Quarkus version

**Describe alternatives you've considered**

**Additional context**

- some specific work is required as automatic depdendabot configuration is failing https://github.com/KaotoIO/kaoto-backend/pull/564

**Comment by apupier** [comment]
maybe better to move directly to Quarkus 3? https://github.com/KaotoIO/kaoto-backend/issues/644

**Comment by mkralik3** [comment]
Skipped. The changes are done as part of Quarkus3 update.
