### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by zetfactor** [KaotoIO/kaoto-backend#610]
**Describe the bug**

I am new to Kaoto.io, and I am trying to run the build as per the Readme.md file, however I keep getting errors.

**To Reproduce**
1. Clone Repo (tried both main branch & release)
2. nvm install (tried both on parent, and inside each module)

**Expected behavior**
Be able to build and run the code as per Readme.MD

**Logs**

[INFO] Reactor Summary for parent 0.7.6:
[INFO]
[INFO] parent ............................................. SUCCESS [  2.015 s]
[INFO] model .............................................. SUCCESS [ 10.345 s]
[INFO] metadata ........................................... SUCCESS [ 31.050 s]
[INFO] catalog ............................................ SUCCESS [  6.985 s]
[INFO] services-interfaces ................................ SUCCESS [  5.829 s]
[INFO] kamelet-support .................................... FAILURE [01:29 min]
[INFO] camel-route-support ................................ SKIPPED
[INFO] cluster ............................................ SKIPPED
[INFO] api ................................................ SKIPPED

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project kamelet-support: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\mz\Downloads\kaoto-backend-0.7.6\kaoto-backend-0.7.6\kamelet-support\target\surefire-reports for the individual test results.`

**Environment **
Windows 10
Maven home: C:\Program Files\Maven\apache-maven-3.9.1
Java version: 17.0.6, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

** I tried**
mvn dependency:resolve -U   <- did not work

**Comment by lhein** [comment]
It is failing for me too.
```
[INFO] Running io.kaoto.backend.model.deployment.kamelet.step.TryCatchTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in io.kaoto.backend.model.deployment.kamelet.step.TryCatchTest
2023-03-31 15:30:50,939 WARN  [io.qua.ope.run.exp.otl.LateBoundBatchSpanProcessor] (main) No BatchSpanProcessor delegate specified, no action taken.
2023-03-31 15:30:51,018 INFO  [io.quarkus] (main) kamelet-support stopped in 0.085s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KameletStepParserServiceTest.checkEIP:218 
...
```

**Comment by apupier** [comment]
this is a known flaky test https://github.com/KaotoIO/kaoto-backend/issues/494
So retrying could fix it.
if you reproduce it on each time, we might ask for your help to investigate on the issue

**Comment by lhein** [comment]
I see that permanently.

**Comment by zetfactor** [comment]
> this is a known flaky test #494 So retrying could fix it. if you reproduce it on each time, we might ask for your help to investigate on the issue

Yes, it occurs multiple times.

**Comment by igarashitm** [comment]
https://github.com/KaotoIO/kaoto-backend/pull/602 will fix the test
