### ISSUE TITLE
Allow to define custom namespace to deploy the integration resource

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-backend#67]
Currently integrations are deployed into default namespace by default. Ideally the default could be actual namespace where backend is deployed.

**Comment by Delawen** [comment]
This is already implemented in the backend API:
https://kaotoio.github.io/kaoto-backend/api/index.html#api-IntegrationResource-integrationsPost

Maybe you wanted to move this to a UI issue?
