### ISSUE TITLE
[BUG] kamelet type is modified from `action` to `sink`

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#719]
**Describe the bug**

`camel.apache.org/kamelet.type: "action"` is modified to `camel.apache.org/kamelet.type: sink`
`name: avro-deserialize-action` is modified to `avro-deserialize-action-sink`

**To Reproduce**

1. Open https://github.com/apache/camel-kamelets/blob/3.20.x/kamelets/avro-deserialize-action.kamelet.yaml with Kaoto

**Expected behavior**

Do nto change the types and name

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**

red.ht/kaoto-snapshots

**Additional context**

it is impacting official Kamelet provided by Apache Camel project

**Comment by Delawen** [comment]
After discussing it with the camel k team, it looks like:

- `source` ends with a `to` that is a `kamelet:sink` or starts with an `uri` in the `from`
 - `sink` ends with a `to` that is NOT a `kamelet:sink`
 - `action` anything else
