### ISSUE TITLE
[BUG] Example and enum tag for property of Kamelet definition are removed

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#720]
**Is your feature request related to a problem? Please describe.**

When opening https://github.com/apache/camel-kamelets/blob/3.20.x/kamelets/avro-serialize-action.kamelet.yaml , the example of schema property is removed

When opening https://github.com/apache/camel-kamelets/blob/3.20.x/kamelets/aws-cloudtrail-source.kamelet.yaml , the enum of region property is removed.

**Describe the solution you'd like**

support example tag

**Describe alternatives you've considered**

**Additional context**

it is impacting kamelet defintion provided by Apache Camel project.

tested with red/ht/kaoto-snapshot

**Comment by Delawen** [comment]
Should be fixed in https://github.com/KaotoIO/kaoto-backend/pull/727

**Comment by apupier** [comment]
> Should be fixed in #727

cool. it will be just a matter of adding/completing a test
