### ISSUE TITLE
[BUG] Invalid `/metadata/name` format for generated ids of Integration

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#723]
**Describe the bug**
The auto-generated `/metadata/name` uses upper case character which is not allowed

> [tomo@p1 camel-k]$ kubectl apply -f example.integration.yaml
The Integration "Integration1687900965845" is invalid: metadata.name: Invalid value: "Integration1687900965845": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**To Reproduce**
1. Choose Integration or Kamelet
2. deploy generated YAML onto k8s

**Expected behavior**
Use lowercase

**Comment by Delawen** [comment]
Oops, good one!
