### ISSUE TITLE
[Java] Deploy Kamelets

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-backend#76]
Right now the deployment endpoint only support KameletBindings. I want to be able to deploy Kamelets too. Potentially... any kind of CRD supported by the backend?

**Comment by Delawen** [comment]
Part of this is #79

**Comment by Delawen** [comment]
Missing: be able to edit parameters on Kamelets.

**Comment by Delawen** [comment]
Part of this is #100

**Comment by kahboom** [comment]
This has been completed.
