### ISSUE TITLE
Content erased when opening google-bigquery-sink.kamelet.yaml

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#762]
### Describe the Bug

When opening https://github.com/apache/camel-kamelets/blob/main/kamelets/google-bigquery-sink.kamelet.yaml , the content of the file is erased.
In console log:
```
TypeError: _a[0] is undefined
    handleChanges SourceCodeEditor.tsx:67
    promise callback*handleChanges SourceCodeEditor.tsx:66
    updateModelFromTheEditor SourceCodeEditor.tsx:118
    onCustomClick CodeEditorControl.js:32
```

### Steps to Reproduce the Bug or Issue

with red.ht/kaoto-snapshots:
1. Open source code editor
2. Paste content https://raw.githubusercontent.com/apache/camel-kamelets/main/kamelets/google-bigquery-sink.kamelet.yaml
3. Click on sync
--> the canvas remains empty

with latest main branches in VS Code:
1. Rightc-ick on the file https://raw.githubusercontent.com/apache/camel-kamelets/main/kamelets/google-bigquery-sink.kamelet.yaml -- >Open with Kaoto graphical editor
2. the canvas is empty and the content of the wile is empty

### Platform

red.ht/kaoto-snapshot

**Comment by lordrip** [comment]
@Delawen using the aforementioned `YAML` returns an empty `FlowsWrapper` :cry:
