### ISSUE TITLE
Using the REST steps generates invalid YAML DSL

### ISSUE THREAD

**Issue by jcordes73** [KaotoIO/kaoto-backend#810]
### Describe the Bug

When using the REST step the resulting YAML DSL is invalid.

It looks like this:

```
- route:
    id: route-1492`
    rest:`
      path: 'null'
```
However it should look like this instead
```
 - rest:
      path: 'null'
```
There should be no route element around it and it should be at the same level as the route element

### Steps to Reproduce the Bug or Issue

1. Go to "Add a step"
2. In "Steps" enter Rest
3. Select the "REST API"/rest step
4. Check the generated YAML

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-ui/assets/2852314/78e3f851-bc7f-4897-980d-281804e8e1f5)

### Platform

- OS: RHEL 8.8 / OpenShift 4.13
- Browser: Firefox
- Version: 102.12.0esr

**Comment by lordrip** [comment]
@Delawen do you think that we could leverage something from what @igarashitm did around `Rest` parsing?
